sudo: required
services:
  - docker

before_install:
  - docker build -t huiqiong0917/react-fib-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true huiqiong0917/react-fib-test npm test -- --coverage

after_success:
  - docker build -t huiqiong0917/multi-client ./client
  - docker build -t huiqiong0917/multi-nginx ./nginx
  - docker build -t huiqiong0917/multi-server ./server
  - docker build -t huiqiong0917/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push huiqiong0917/multi-client
  - docker push huiqiong0917/multi-nginx
  - docker push huiqiong0917/multi-server
  - docker push huiqiong0917/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker-container"
  env: "Multi-docker-container-env"
  bucket_name: "elasticbeanstalk-us-east-2-767397758338"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
