sudo: required
services:
  - docker

before_install:
  - docker build -t huiqiong0917/react-fib-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true huiqiong0917/react-fib-test npm test -- --coverage

after_success:
  - docker build -t huiqiong0917/multi-client ./client
  - docker build -t huiqiong0917/multi-nginx ./nginx
  - docker build -t huiqiong0917/multi-server ./server
  - docker build -t huiqiong0917/multi-worker ./worker
